from __future__ import annotations

import importlib.util
from pathlib import Path


def test_main_generates_uv_lock_when_missing(
    monkeypatch,
    tmp_path: Path,
) -> None:
    module = _load_update_local_wheel_metadata_module()
    pyproject_path = tmp_path / "pyproject.toml"
    uv_lock_path = tmp_path / "uv.lock"
    wheel_path = tmp_path / "vendor" / "m8flow_bpmn_core-0.2.0-py3-none-any.whl"
    wheel_path.parent.mkdir()
    wheel_path.write_bytes(b"sample-wheel")
    pyproject_path.write_text(
        """
[tool.uv.sources]
m8flow-bpmn-core = { path = "vendor/m8flow_bpmn_core-0.1.0-py3-none-any.whl" }
""".strip()
        + "\n",
        encoding="utf-8",
    )

    captured: dict[str, object] = {}

    def fake_generate_uv_lock(
        *,
        pyproject_path: Path,
        uv_lock_path: Path,
        uv_executable: str,
    ) -> None:
        captured["pyproject_path"] = pyproject_path
        captured["uv_lock_path"] = uv_lock_path
        captured["uv_executable"] = uv_executable
        uv_lock_path.write_text("# generated by test\n", encoding="utf-8")

    monkeypatch.setattr(module, "_generate_uv_lock", fake_generate_uv_lock)
    monkeypatch.setattr(
        "sys.argv",
        [
            "update_local_wheel_metadata.py",
            "--pyproject-path",
            str(pyproject_path),
            "--uv-lock-path",
            str(uv_lock_path),
            "--wheel-path",
            str(wheel_path),
            "--uv-executable",
            "uv-test",
        ],
    )

    assert module.main() == 0
    assert pyproject_path.read_text(encoding="utf-8") == (
        '[tool.uv.sources]\n'
        'm8flow-bpmn-core = { path = "vendor/m8flow_bpmn_core-0.2.0-py3-none-any.whl" }\n'
    )
    assert uv_lock_path.read_text(encoding="utf-8") == "# generated by test\n"
    assert captured == {
        "pyproject_path": pyproject_path,
        "uv_lock_path": uv_lock_path,
        "uv_executable": "uv-test",
    }


def test_main_updates_existing_uv_lock_in_place(
    monkeypatch,
    tmp_path: Path,
) -> None:
    module = _load_update_local_wheel_metadata_module()
    pyproject_path = tmp_path / "pyproject.toml"
    uv_lock_path = tmp_path / "uv.lock"
    wheel_path = tmp_path / "vendor" / "m8flow_bpmn_core-0.2.0-py3-none-any.whl"
    wheel_path.parent.mkdir()
    wheel_path.write_bytes(b"sample-wheel")
    pyproject_path.write_text(
        """
[tool.uv.sources]
m8flow-bpmn-core = { path = "vendor/m8flow_bpmn_core-0.1.0-py3-none-any.whl" }
""".strip()
        + "\n",
        encoding="utf-8",
    )
    uv_lock_path.write_text(
        """
[[package]]
name = "m8flow-bpmn-core"
version = "0.1.0"
source = { path = "vendor/m8flow_bpmn_core-0.1.0-py3-none-any.whl" }
wheels = [{ filename = "m8flow_bpmn_core-0.1.0-py3-none-any.whl", hash = "sha256:oldhash" }]

[[package]]
name = "m8flow-bpmn-core-sample-app"
version = "0.1.0"
dependencies = [
    { name = "m8flow-bpmn-core", path = "vendor/m8flow_bpmn_core-0.1.0-py3-none-any.whl" },
]
""".strip()
        + "\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(
        "sys.argv",
        [
            "update_local_wheel_metadata.py",
            "--pyproject-path",
            str(pyproject_path),
            "--uv-lock-path",
            str(uv_lock_path),
            "--wheel-path",
            str(wheel_path),
        ],
    )

    assert module.main() == 0
    updated_lock_text = uv_lock_path.read_text(encoding="utf-8")
    assert 'version = "0.2.0"' in updated_lock_text
    assert (
        'source = { path = "vendor/m8flow_bpmn_core-0.2.0-py3-none-any.whl" }'
        in updated_lock_text
    )
    assert (
        '{ name = "m8flow-bpmn-core", path = "vendor/m8flow_bpmn_core-0.2.0-py3-none-any.whl" }'
        in updated_lock_text
    )


def _load_update_local_wheel_metadata_module():
    script_path = (
        Path(__file__).resolve().parents[1]
        / "scripts"
        / "update_local_wheel_metadata.py"
    )
    spec = importlib.util.spec_from_file_location(
        "sample_app_update_local_wheel_metadata",
        script_path,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load module spec for '{script_path}'.")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module
