"""add future task runtime table"""

import sqlalchemy as sa
from alembic import op

revision = "250e246bc7a4"
down_revision = "e71b5d358601"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "future_task",
        sa.Column("guid", sa.String(length=36), nullable=False),
        sa.Column("run_at_in_seconds", sa.Integer(), nullable=False),
        sa.Column("queued_to_run_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column(
            "archived_for_process_instance_status",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("updated_at_in_seconds", sa.Integer(), nullable=False),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["guid"], ["task.guid"], name="future_task_task_guid_fk", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_future_task_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.PrimaryKeyConstraint("guid", name=op.f("pk_future_task")),
    )
    with op.batch_alter_table("future_task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_future_task_archived_for_process_instance_status"),
            ["archived_for_process_instance_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_future_task_completed"), ["completed"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_future_task_m8f_tenant_id"), ["m8f_tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_future_task_queued_to_run_at_in_seconds"),
            ["queued_to_run_at_in_seconds"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_future_task_run_at_in_seconds"),
            ["run_at_in_seconds"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("future_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_future_task_run_at_in_seconds"))
        batch_op.drop_index(batch_op.f("ix_future_task_queued_to_run_at_in_seconds"))
        batch_op.drop_index(batch_op.f("ix_future_task_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_future_task_completed"))
        batch_op.drop_index(
            batch_op.f("ix_future_task_archived_for_process_instance_status")
        )

    op.drop_table("future_task")
    # ### end Alembic commands ###
