"""initial schema"""

import sqlalchemy as sa
from alembic import op

revision = "e71b5d358601"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "m8flow_tenant",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_m8flow_tenant")),
    )
    with op.batch_alter_table("m8flow_tenant", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_m8flow_tenant_slug"), ["slug"], unique=True
        )

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "bpmn_process_definition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("single_process_hash", sa.String(length=255), nullable=False),
        sa.Column("full_process_model_hash", sa.String(length=255), nullable=True),
        sa.Column("bpmn_identifier", sa.String(length=255), nullable=False),
        sa.Column("bpmn_name", sa.String(length=255), nullable=True),
        sa.Column("properties_json", sa.JSON(), nullable=False),
        sa.Column("bpmn_version_control_type", sa.String(length=50), nullable=True),
        sa.Column(
            "bpmn_version_control_identifier", sa.String(length=255), nullable=True
        ),
        sa.Column("updated_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_bpmn_process_definition_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bpmn_process_definition")),
        sa.UniqueConstraint(
            "m8f_tenant_id",
            "full_process_model_hash",
            "single_process_hash",
            name="process_hash_unique",
        ),
        sa.UniqueConstraint(
            "m8f_tenant_id",
            "full_process_model_hash",
            name="bpmn_process_definition_full_process_model_hash_tenant_unique",
        ),
    )
    with op.batch_alter_table("bpmn_process_definition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_definition_bpmn_identifier"),
            ["bpmn_identifier"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_definition_bpmn_name"),
            ["bpmn_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_definition_m8f_tenant_id"),
            ["m8f_tenant_id"],
            unique=False,
        )

    op.create_table(
        "bpmn_process",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.String(length=36), nullable=True),
        sa.Column("bpmn_process_definition_id", sa.Integer(), nullable=False),
        sa.Column("top_level_process_id", sa.Integer(), nullable=True),
        sa.Column("direct_parent_process_id", sa.Integer(), nullable=True),
        sa.Column("properties_json", sa.JSON(), nullable=False),
        sa.Column("json_data_hash", sa.String(length=255), nullable=False),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["bpmn_process_definition_id"],
            ["bpmn_process_definition.id"],
            name=op.f(
                "fk_bpmn_process_bpmn_process_definition_id_bpmn_process_definition"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["direct_parent_process_id"],
            ["bpmn_process.id"],
            name=op.f("fk_bpmn_process_direct_parent_process_id_bpmn_process"),
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_bpmn_process_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.ForeignKeyConstraint(
            ["top_level_process_id"],
            ["bpmn_process.id"],
            name=op.f("fk_bpmn_process_top_level_process_id_bpmn_process"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bpmn_process")),
        sa.UniqueConstraint("guid", name=op.f("uq_bpmn_process_guid")),
    )
    with op.batch_alter_table("bpmn_process", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_bpmn_process_definition_id"),
            ["bpmn_process_definition_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_direct_parent_process_id"),
            ["direct_parent_process_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_json_data_hash"),
            ["json_data_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_m8f_tenant_id"), ["m8f_tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bpmn_process_top_level_process_id"),
            ["top_level_process_id"],
            unique=False,
        )

    op.create_table(
        "task_definition",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bpmn_process_definition_id", sa.Integer(), nullable=False),
        sa.Column("bpmn_identifier", sa.String(length=255), nullable=False),
        sa.Column("bpmn_name", sa.String(length=255), nullable=True),
        sa.Column("typename", sa.String(length=255), nullable=False),
        sa.Column("properties_json", sa.JSON(), nullable=False),
        sa.Column("updated_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["bpmn_process_definition_id"],
            ["bpmn_process_definition.id"],
            name=op.f(
                "fk_task_definition_bpmn_process_definition_id_bpmn_process_definition"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_task_definition_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_definition")),
        sa.UniqueConstraint(
            "m8f_tenant_id",
            "bpmn_process_definition_id",
            "bpmn_identifier",
            name="task_definition_unique",
        ),
    )
    with op.batch_alter_table("task_definition", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_definition_bpmn_identifier"),
            ["bpmn_identifier"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_task_definition_bpmn_name"), ["bpmn_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_definition_bpmn_process_definition_id"),
            ["bpmn_process_definition_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_task_definition_m8f_tenant_id"),
            ["m8f_tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_task_definition_typename"), ["typename"], unique=False
        )

    op.create_table(
        "process_instance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_model_identifier", sa.String(length=255), nullable=False),
        sa.Column("process_model_display_name", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.String(length=255), nullable=True),
        sa.Column("process_initiator_id", sa.Integer(), nullable=True),
        sa.Column("bpmn_process_definition_id", sa.Integer(), nullable=True),
        sa.Column("bpmn_process_id", sa.Integer(), nullable=True),
        sa.Column("process_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("start_in_seconds", sa.Integer(), nullable=True),
        sa.Column("end_in_seconds", sa.Integer(), nullable=True),
        sa.Column("updated_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at_in_seconds", sa.Integer(), nullable=True),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["bpmn_process_definition_id"],
            ["bpmn_process_definition.id"],
            name=op.f(
                "fk_process_instance_bpmn_process_definition_id_bpmn_process_definition"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["bpmn_process_id"],
            ["bpmn_process.id"],
            name=op.f("fk_process_instance_bpmn_process_id_bpmn_process"),
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_process_instance_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.ForeignKeyConstraint(
            ["process_initiator_id"],
            ["user.id"],
            name=op.f("fk_process_instance_process_initiator_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_instance")),
    )
    with op.batch_alter_table("process_instance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_process_instance_bpmn_process_definition_id"),
            ["bpmn_process_definition_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_bpmn_process_id"),
            ["bpmn_process_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_end_in_seconds"),
            ["end_in_seconds"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_m8f_tenant_id"),
            ["m8f_tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_process_initiator_id"),
            ["process_initiator_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_process_model_display_name"),
            ["process_model_display_name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_process_model_identifier"),
            ["process_model_identifier"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_start_in_seconds"),
            ["start_in_seconds"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_process_instance_status"), ["status"], unique=False
        )

    op.create_table(
        "task",
        sa.Column("guid", sa.String(length=36), nullable=False),
        sa.Column("bpmn_process_id", sa.Integer(), nullable=False),
        sa.Column("process_instance_id", sa.Integer(), nullable=False),
        sa.Column("task_definition_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("properties_json", sa.JSON(), nullable=False),
        sa.Column("json_data_hash", sa.String(length=255), nullable=False),
        sa.Column("python_env_data_hash", sa.String(length=255), nullable=False),
        sa.Column("runtime_info", sa.JSON(), nullable=True),
        sa.Column("start_in_seconds", sa.Integer(), nullable=True),
        sa.Column("end_in_seconds", sa.Integer(), nullable=True),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["bpmn_process_id"],
            ["bpmn_process.id"],
            name=op.f("fk_task_bpmn_process_id_bpmn_process"),
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_task_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instance.id"],
            name=op.f("fk_task_process_instance_id_process_instance"),
        ),
        sa.ForeignKeyConstraint(
            ["task_definition_id"],
            ["task_definition.id"],
            name=op.f("fk_task_task_definition_id_task_definition"),
        ),
        sa.PrimaryKeyConstraint("guid", name=op.f("pk_task")),
    )
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_bpmn_process_id"), ["bpmn_process_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_json_data_hash"), ["json_data_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_m8f_tenant_id"), ["m8f_tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_task_process_instance_id"),
            ["process_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_task_python_env_data_hash"),
            ["python_env_data_hash"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_task_state"), ["state"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_task_task_definition_id"),
            ["task_definition_id"],
            unique=False,
        )

    op.create_table(
        "human_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("process_instance_id", sa.Integer(), nullable=False),
        sa.Column("task_guid", sa.String(length=36), nullable=True),
        sa.Column("lane_assignment_id", sa.Integer(), nullable=True),
        sa.Column("completed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("actual_owner_id", sa.Integer(), nullable=True),
        sa.Column("task_name", sa.String(length=255), nullable=False),
        sa.Column("task_title", sa.String(length=255), nullable=True),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("task_status", sa.String(length=50), nullable=False),
        sa.Column("process_model_display_name", sa.String(length=255), nullable=False),
        sa.Column("bpmn_process_identifier", sa.String(length=255), nullable=False),
        sa.Column("lane_name", sa.String(length=255), nullable=True),
        sa.Column("json_metadata", sa.JSON(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["actual_owner_id"],
            ["user.id"],
            name=op.f("fk_human_task_actual_owner_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["completed_by_user_id"],
            ["user.id"],
            name=op.f("fk_human_task_completed_by_user_id_user"),
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_human_task_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.ForeignKeyConstraint(
            ["process_instance_id"],
            ["process_instance.id"],
            name=op.f("fk_human_task_process_instance_id_process_instance"),
        ),
        sa.ForeignKeyConstraint(
            ["task_guid"], ["task.guid"], name=op.f("fk_human_task_task_guid_task")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_task")),
    )
    with op.batch_alter_table("human_task", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_human_task_actual_owner_id"),
            ["actual_owner_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_completed"), ["completed"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_completed_by_user_id"),
            ["completed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_lane_assignment_id"),
            ["lane_assignment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_m8f_tenant_id"), ["m8f_tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_process_instance_id"),
            ["process_instance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_task_guid"), ["task_guid"], unique=False
        )

    op.create_table(
        "human_task_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("human_task_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("added_by", sa.String(length=20), nullable=True),
        sa.Column("m8f_tenant_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["human_task_id"],
            ["human_task.id"],
            name=op.f("fk_human_task_user_human_task_id_human_task"),
        ),
        sa.ForeignKeyConstraint(
            ["m8f_tenant_id"],
            ["m8flow_tenant.id"],
            name=op.f("fk_human_task_user_m8f_tenant_id_m8flow_tenant"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_human_task_user_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_task_user")),
        sa.UniqueConstraint("human_task_id", "user_id", name="human_task_user_unique"),
    )
    with op.batch_alter_table("human_task_user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_human_task_user_added_by"), ["added_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_user_human_task_id"),
            ["human_task_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_user_m8f_tenant_id"),
            ["m8f_tenant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_human_task_user_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("human_task_user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_human_task_user_user_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_user_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_user_human_task_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_user_added_by"))

    op.drop_table("human_task_user")
    with op.batch_alter_table("human_task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_human_task_task_guid"))
        batch_op.drop_index(batch_op.f("ix_human_task_process_instance_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_lane_assignment_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_completed_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_human_task_completed"))
        batch_op.drop_index(batch_op.f("ix_human_task_actual_owner_id"))

    op.drop_table("human_task")
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_task_definition_id"))
        batch_op.drop_index(batch_op.f("ix_task_state"))
        batch_op.drop_index(batch_op.f("ix_task_python_env_data_hash"))
        batch_op.drop_index(batch_op.f("ix_task_process_instance_id"))
        batch_op.drop_index(batch_op.f("ix_task_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_task_json_data_hash"))
        batch_op.drop_index(batch_op.f("ix_task_bpmn_process_id"))

    op.drop_table("task")
    with op.batch_alter_table("process_instance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_process_instance_status"))
        batch_op.drop_index(batch_op.f("ix_process_instance_start_in_seconds"))
        batch_op.drop_index(batch_op.f("ix_process_instance_process_model_identifier"))
        batch_op.drop_index(
            batch_op.f("ix_process_instance_process_model_display_name")
        )
        batch_op.drop_index(batch_op.f("ix_process_instance_process_initiator_id"))
        batch_op.drop_index(batch_op.f("ix_process_instance_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_process_instance_end_in_seconds"))
        batch_op.drop_index(batch_op.f("ix_process_instance_bpmn_process_id"))
        batch_op.drop_index(
            batch_op.f("ix_process_instance_bpmn_process_definition_id")
        )

    op.drop_table("process_instance")
    with op.batch_alter_table("task_definition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_definition_typename"))
        batch_op.drop_index(batch_op.f("ix_task_definition_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_task_definition_bpmn_process_definition_id"))
        batch_op.drop_index(batch_op.f("ix_task_definition_bpmn_name"))
        batch_op.drop_index(batch_op.f("ix_task_definition_bpmn_identifier"))

    op.drop_table("task_definition")
    with op.batch_alter_table("bpmn_process", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bpmn_process_top_level_process_id"))
        batch_op.drop_index(batch_op.f("ix_bpmn_process_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bpmn_process_json_data_hash"))
        batch_op.drop_index(batch_op.f("ix_bpmn_process_direct_parent_process_id"))
        batch_op.drop_index(batch_op.f("ix_bpmn_process_bpmn_process_definition_id"))

    op.drop_table("bpmn_process")
    with op.batch_alter_table("bpmn_process_definition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bpmn_process_definition_m8f_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bpmn_process_definition_bpmn_name"))
        batch_op.drop_index(batch_op.f("ix_bpmn_process_definition_bpmn_identifier"))

    op.drop_table("bpmn_process_definition")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("m8flow_tenant", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_m8flow_tenant_slug"))

    op.drop_table("m8flow_tenant")
    # ### end Alembic commands ###
